name: Docker

on:
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/BoltzExchange/regtest
  
jobs:
  # Push image to GitHub Packages.
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run:  python3 ./docker/build.py buildx regtest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Push image
        run: docker push $IMAGE_NAME:latest
